Fix compilation error introduced on previous merge
Fix the following compilation error introduced on SHA:24d792053a0d4099e4ebec5a4f015b0c2a1cbf29

```
yafolding.el:148:13: Warning: the function ‘yafolding--current-indentation’ is
    not known to be defined.
```